use eframe::egui;
use egui::{Color32, FontId, Stroke};

#[derive(Debug)]
pub struct Style {
    pub heading_font: FontId,
    pub body_font: FontId,
    pub sub_font: FontId,

    pub text_color: Color32,
    pub widget_text_color: Color32,
    pub widget_noninteractive_text_color: Color32,
    pub widget_noninteractive_bg_fill: Color32,
    pub widget_active_bg_fill: Color32,
    pub widget_hover_bg_fill: Color32,
    pub widget_inactive_bg_fill: Color32,
    pub widget_inactive_bg_stroke: Stroke,
    pub port_radius: f32,
    pub port_activation_radius: f32,
    pub header_text_offset: f32,
    pub cache_button_width_factor: f32,
    pub cache_button_vertical_pad_factor: f32,
    pub cache_button_text_pad_factor: f32,
    pub cache_active_color: Color32,
    pub cache_checked_text_color: Color32,
    pub status_terminal_color: Color32,
    pub status_impure_color: Color32,
    pub status_dot_radius: f32,
    pub status_item_gap: f32,
    pub input_port_color: Color32,
    pub output_port_color: Color32,
    pub input_hover_color: Color32,
    pub output_hover_color: Color32,
    pub connection_stroke: Stroke,
    pub connection_highlight_stroke: Stroke,
    pub temp_connection_stroke: Stroke,
    pub breaker_stroke: Stroke,
    pub dotted_color: Color32,
    pub dotted_base_spacing: f32,
    pub dotted_radius_base: f32,
    pub dotted_radius_min: f32,
    pub dotted_radius_max: f32,
    pub node: NodeStyle,
}

#[derive(Debug)]
pub struct NodeStyle {
    pub width: f32,
    pub header_height: f32,
    pub cache_height: f32,
    pub row_height: f32,
    pub padding: f32,
    pub corner_radius: f32,
    pub fill: Color32,
    pub stroke: Stroke,
    pub const_stroke: Stroke,
    pub selected_stroke: Stroke,
}

impl Style {
    pub fn new() -> Self {
        Self {
            heading_font: FontId {
                size: 18.0,
                family: egui::FontFamily::Proportional,
            },
            body_font: FontId {
                size: 15.0,
                family: egui::FontFamily::Proportional,
            },
            sub_font: FontId {
                size: 13.0,
                family: egui::FontFamily::Proportional,
            },
            text_color: Color32::from_rgb(192, 192, 192),
            widget_text_color: Color32::from_rgb(192, 192, 192),
            widget_noninteractive_text_color: Color32::from_rgb(140, 140, 140),
            widget_noninteractive_bg_fill: Color32::from_rgb(35, 35, 35),
            widget_active_bg_fill: Color32::from_rgb(60, 60, 60),
            widget_hover_bg_fill: Color32::from_rgb(50, 50, 50),
            widget_inactive_bg_fill: Color32::from_rgb(40, 40, 40),
            widget_inactive_bg_stroke: Stroke::new(1.0, Color32::from_rgb(65, 65, 65)),
            port_radius: 18.0 * 0.3,
            port_activation_radius: 18.0 * 0.3 * 1.5,
            header_text_offset: 4.0,
            cache_button_width_factor: 3.1,
            cache_button_vertical_pad_factor: 0.4,
            cache_button_text_pad_factor: 0.5,
            cache_active_color: Color32::from_rgb(240, 205, 90),
            cache_checked_text_color: Color32::from_rgb(60, 50, 20),
            status_terminal_color: Color32::from_rgb(128, 128, 128),
            status_impure_color: Color32::from_rgb(255, 150, 70),
            status_dot_radius: 4.0,
            status_item_gap: 6.0,
            input_port_color: Color32::from_rgb(70, 150, 255),
            output_port_color: Color32::from_rgb(70, 200, 200),
            input_hover_color: Color32::from_rgb(120, 190, 255),
            output_hover_color: Color32::from_rgb(110, 230, 210),
            connection_stroke: Stroke::new(2.0, Color32::from_rgb(70, 150, 255)),
            connection_highlight_stroke: Stroke::new(2.0, Color32::from_rgb(255, 90, 90)),
            temp_connection_stroke: Stroke::new(2.0, Color32::from_rgb(170, 200, 255)),
            breaker_stroke: Stroke::new(2.0, Color32::from_rgb(255, 120, 120)),
            dotted_color: Color32::from_rgb(48, 48, 48),
            dotted_base_spacing: 24.0,
            dotted_radius_base: 1.2,
            dotted_radius_min: 0.6,
            dotted_radius_max: 2.4,
            node: NodeStyle {
                width: 180.0,
                header_height: 22.0,
                cache_height: 20.0,
                row_height: 18.0,
                padding: 8.0,
                corner_radius: 6.0,
                fill: Color32::from_rgb(27, 27, 27),
                stroke: Stroke::new(1.0, Color32::from_rgb(60, 60, 60)),
                selected_stroke: Stroke::new(1.0, Color32::from_rgb(128, 128, 128)),
                const_stroke: Stroke::new(1.0, Color32::from_rgb(70, 150, 255)),
            },
        }
    }
}
