use common::SerdeFormat;
use palantir::Color;

/// Built-in default theme, embedded at compile time. Generated by the
/// Theme → Export menu and checked in; `Theme::default` deserializes
/// it so the on-disk theme format is the single source of truth for
/// darkroom's default look (no parallel hand-coded palette to drift).
const DEFAULT_THEME_TOML: &str = include_str!("../assets/ayu-graphite.toml");

/// Visual palette + layout dimensions for darkroom's UI. Owned by
/// `MainWindow`, handed to every UI subtree through
/// [`crate::app::AppContext`] so call sites read off a single source
/// instead of hard-coded constants. Layout fields live here too —
/// node ports, value editors, etc. — so a theme swap can restyle
/// geometry as well as color.
///
/// Also owns the palantir [`palantir::Theme`] this app wants on its
/// `Ui`. [`crate::app::App::new`] copies `palantir_theme` into
/// `ui.theme` once before the first frame, so palantir-side widgets
/// (buttons, text edits, menus, scrollbars) read from the same source.
/// Tweak fields on `theme.palantir_theme` during construction to
/// override palantir's defaults.
///
/// Serializable so the whole bundle (palantir palette + darkroom
/// layout + colors) round-trips through Rhai for the Theme → Load /
/// Export menu.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct Theme {
    // Scalar (`Color` / `f32`) fields come first; `palantir_theme`
    // (a nested table) is last. TOML serialization requires every
    // scalar value to precede any table at the same level — otherwise
    // the serializer errors with `ValueAfterTable`.

    // ── canvas ────────────────────────────────────────────────────
    pub canvas_bg: Color,
    /// Tint of the rubber-band multi-selection rectangle. Drawn as a
    /// translucent fill plus a near-opaque 1px border, both derived
    /// from this single color (palette accent).
    pub selection_rect: Color,
    /// Dotted backdrop grid: dot color, world-space base spacing
    /// between dots, and on-screen dot radius (px). Spacing is wrapped
    /// by a power-of-2 multiplier as the user zooms so the field never
    /// collapses into noise — see `gui::background`.
    pub canvas_dot: Color,
    pub canvas_dot_spacing: f32,
    pub canvas_dot_radius: f32,

    // ── connections ──────────────────────────────────────────────
    pub connection_broken: Color,
    pub connection_width: f32,
    pub breaker_stroke: Color,
    pub breaker_stroke_width: f32,

    // ── node chrome ──────────────────────────────────────────────
    pub node_fill: Color,
    pub node_border: Color,
    pub node_border_width: f32,
    pub node_corner_radius: f32,
    /// Minimum content size for a node body. Caps how tightly a node
    /// with very short port labels can shrink horizontally so the
    /// header stays legible at any zoom.
    pub node_min_width: f32,
    pub node_min_height: f32,

    pub header_fill: Color,
    pub header_corner_radius: f32,

    /// Glow color painted behind the selected node — picked brighter
    /// than `canvas_bg` so the halo reads as a highlight, not noise.
    pub selection_glow: Color,

    /// Top-chrome fill behind the menu bar + tab strip. Palette `bg`
    /// (`#252525`) — a notch darker than the node surface, sitting
    /// between the graph (`canvas_bg`) and the nodes, so the chrome
    /// recedes and the active tab (which uses `canvas_bg`) reads as
    /// continuous with the graph below it. `#[serde(default)]` so older
    /// themes keep loading without regenerating the asset.
    #[serde(default = "default_chrome_fill")]
    pub chrome_fill: Color,

    // ── header badges ────────────────────────────────────────────
    // Indicator-chip accents in the node header. `#[serde(default)]`
    // so themes predating these fields still load (the embedded asset
    // doesn't need regenerating to pick up new chips).
    /// Subgraph (composite instance) chip — accent cyan.
    #[serde(default = "default_badge_subgraph")]
    pub badge_subgraph: Color,
    /// Terminal (sink) chip — error red.
    #[serde(default = "default_badge_terminal")]
    pub badge_terminal: Color,
    /// Cache (compute-once) chip — warning yellow.
    #[serde(default = "default_badge_cache")]
    pub badge_cache: Color,

    // ── ports ────────────────────────────────────────────────────
    pub input_port: Color,
    pub output_port: Color,
    pub input_port_hover: Color,
    pub output_port_hover: Color,
    /// Side of the port circle quad. The circle's corner radius is
    /// derived as `port_size * 0.5` (see [`Self::port_radius`]).
    pub port_size: f32,
    /// Vertical inset at the top of each port column (gap below the
    /// header band before the first port).
    pub port_col_pad_top: f32,
    /// Horizontal inset on each side of the ports row. Port circles
    /// overhang by `-(port_radius + port_col_pad_x)` so they straddle
    /// the node body edge regardless of this inset.
    pub port_col_pad_x: f32,
    /// Vertical gap between adjacent ports in a column.
    pub port_gap: f32,
    /// Horizontal gap between the input and output port columns.
    pub port_cols_gap: f32,

    // ── inline editors / popups ─────────────────────────────────
    /// Fixed width of the inline static-value editor that hugs a
    /// `Binding::Const` input port.
    pub value_editor_width: f32,
    /// Cap on the new-node popup's height. Inner scroll handles
    /// overflow when the function list exceeds the cap.
    pub new_node_popup_max_height: f32,

    /// Palantir-side widget theme. Pushed onto `Ui::theme` once at
    /// startup so every palantir widget (Button, TextEdit, MenuItem,
    /// Scroll, Tooltip…) reads a darkroom-tuned palette without each
    /// call site restyling per use. Last field so its TOML table
    /// follows all the scalar fields above (TOML `ValueAfterTable`).
    pub palantir_theme: palantir::Theme,
}

fn default_chrome_fill() -> Color {
    Color::hex(0x252525)
}

fn default_badge_subgraph() -> Color {
    Color::hex(0x9adbfb)
}

fn default_badge_terminal() -> Color {
    Color::hex(0xff5e44)
}

fn default_badge_cache() -> Color {
    Color::hex(0xffd44a)
}

impl Theme {
    /// Derived radius for port circles — half the port side. Lives as
    /// a method instead of a stored field so the two can't drift if
    /// someone bumps `port_size` and forgets the radius.
    #[inline]
    pub fn port_radius(&self) -> f32 {
        self.port_size * 0.5
    }
}

impl Default for Theme {
    /// Deserialize the embedded `ayu-graphite.toml`. The asset is a
    /// checked-in build artifact we control, so a parse failure is a
    /// build/test bug, not a runtime condition — `expect` rather than
    /// a silent fallback so drift surfaces loudly (the theme tests
    /// construct `Theme::default()` and would fail).
    fn default() -> Self {
        common::deserialize(DEFAULT_THEME_TOML.as_bytes(), SerdeFormat::Toml)
            .expect("embedded ayu-graphite.toml theme should deserialize")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// One-shot: regenerate `assets/ayu-graphite.toml` from the current
    /// default, with menu-bar triggers and popup rows shrunk to 13 px
    /// (palantir's own defaults stay 16 px — the smaller menu scale is
    /// a darkroom theme choice, baked into the asset as data). Run with
    /// `cargo test -p darkroom generate_toml_asset -- --ignored`.
    #[test]
    #[ignore = "one-shot asset generator"]
    fn generate_toml_asset() {
        use palantir::{Brush, WidgetLook};

        let mut theme = Theme::default();
        let base = theme.palantir_theme.text;
        let shrink = |look: &mut WidgetLook| {
            look.text = Some(look.text.unwrap_or(base).with_font_size(13.0));
        };
        // At rest the menu bar floats over the graph, so give the
        // triggers a semi-transparent chip — legible against busy nodes
        // while still letting them hint through. Color derives from the
        // theme's node surface so it tracks palette changes.
        let chip = Brush::Solid(theme.node_fill.with_alpha(0.85));
        let mb = &mut theme.palantir_theme.menu_button;
        shrink(&mut mb.normal);
        shrink(&mut mb.hovered);
        shrink(&mut mb.pressed);
        shrink(&mut mb.disabled);
        if let Some(bg) = mb.normal.background.as_mut() {
            bg.fill = chip.clone();
        }
        if let Some(bg) = mb.disabled.background.as_mut() {
            bg.fill = chip;
        }
        let item = &mut theme.palantir_theme.context_menu.item;
        shrink(&mut item.normal);
        shrink(&mut item.hovered);
        shrink(&mut item.disabled);

        let bytes = common::serialize(&theme, SerdeFormat::Toml);
        std::fs::write("assets/ayu-graphite.toml", bytes).expect("write toml asset");
    }

    /// The whole bundle — darkroom's own fields *and* the nested
    /// palantir palette — must survive a TOML round-trip; that's the
    /// on-disk format the Theme → Load / Export menu and the config
    /// rely on. Exercises the formerly-fragile case too: the tooltip's
    /// infinite max-size axis (handled by `Size`'s custom serde).
    #[test]
    fn theme_roundtrips_through_toml() {
        let mut theme = Theme {
            node_min_width: 137.5,
            selection_glow: Color::hex(0x123456),
            ..Theme::default()
        };
        theme.palantir_theme.window_clear = Color::hex(0xabcdef);

        let bytes = common::serialize(&theme, SerdeFormat::Toml);
        let back: Theme = common::deserialize(&bytes, SerdeFormat::Toml)
            .expect("theme should deserialize from its own TOML output");

        assert_eq!(back.node_min_width, 137.5);
        assert_eq!(back.selection_glow, Color::hex(0x123456));
        assert_eq!(back.canvas_bg, theme.canvas_bg);
        // Nested palantir palette round-trips too.
        assert_eq!(back.palantir_theme.window_clear, Color::hex(0xabcdef));
        // The infinite tooltip-height axis survives `Size`'s serde.
        assert!(back.palantir_theme.tooltip.max_size.h.is_infinite());
        assert_eq!(back.palantir_theme.tooltip.max_size.w, 280.0);
    }

    /// `Theme::default` deserializes the embedded `ayu-graphite.toml`.
    /// Pins a darkroom field and a nested palantir field against the
    /// asset so a malformed or drifted checked-in theme fails loudly
    /// at test time instead of panicking the running app.
    #[test]
    fn default_loads_embedded_theme() {
        let theme = Theme::default();
        // Ayu Mirage High Contrast: canvas = terminal_bg, ports use
        // success-green / syn-keyword-orange.
        assert_eq!(theme.canvas_bg, Color::hex(0x1a1a1a));
        assert_eq!(theme.input_port, Color::hex(0xdaff58));
        assert_eq!(theme.output_port, Color::hex(0xffa63d));
        assert_eq!(theme.node_min_width, 160.0);
        assert!(theme.palantir_theme.tooltip.max_size.h.is_infinite());
    }
}
