// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CoreInterop
{
    internal static unsafe partial class CoreNative
    {
        const string __DllName = "core_interop";



        [DllImport(__DllName, EntryPoint = "create_context", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* create_context();

        [DllImport(__DllName, EntryPoint = "destroy_context", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void destroy_context(byte* ctx);

        [DllImport(__DllName, EntryPoint = "dummy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void dummy(FfiBuf _a);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct FfiBuf
    {
        public byte* bytes;
        public uint length;
        public uint capacity;
    }



}
