[package]
name = "cs_interop"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
common = { workspace = true }
imaginarium = { workspace = true }
graph = { workspace = true }
uuid = { version = "1.8.0", features = ["v4"] }

[build-dependencies]
csbindgen = "1.9"
