[package]
name = "cs_interop"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
common = { workspace = true }
imaginarium = { workspace = true }
graph = { workspace = true }
uuid = { workspace = true }
bytes = { workspace = true }

